import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  CheckCircle2,
  Clock,
  Lock,
  Sparkles,
  ArrowRight,
  Calendar,
  PlayCircle,
  Target
} from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import learningService from '../services/learningService';
import ResourceCard from '../components/ResourceCard';
import Loading from '../components/Loading';

export const LearningPath = () => {
  const navigate = useNavigate();
  const { currentUser } = useAuth();
  const [selectedRole, setSelectedRole] = useState(currentUser?.targetRole || 'Full-Stack Developer');
  const [roadmap, setRoadmap] = useState([]);
  const [resources, setResources] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      try {
        const [rm, res] = await Promise.all([
          learningService.getRoadmap(selectedRole),
          learningService.getResources()
        ]);
        setRoadmap(rm);
        setResources(res);
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, [selectedRole]);

  if (loading) {
    return <Loading type="pulse" text="Assembling your personalized curriculum..." />;
  }

  const getStatusBadge = (status) => {
    switch (status.toLowerCase()) {
      case 'completed':
        return {
          bg: 'bg-[#DCFCE7] border-[#BBF7D0] text-[#16A34A]',
          icon: <CheckCircle2 className="w-3.5 h-3.5 text-[#16A34A]" />,
          label: 'Completed'
        };
      case 'in progress':
        return {
          bg: 'bg-[#F0FDFA] border-[#CCFBF1] text-[#0F766E]',
          icon: <Clock className="w-3.5 h-3.5 text-[#0F766E]" />,
          label: 'In Progress'
        };
      case 'recommended':
        return {
          bg: 'bg-[#FEF3C7] border-[#FDE68A] text-[#D97706]',
          icon: <Sparkles className="w-3.5 h-3.5 text-[#D97706]" />,
          label: 'AI Recommended Next'
        };
      case 'locked':
      default:
        return {
          bg: 'bg-[#F1F5F9] border-[#E2E8F0] text-[#94A3B8]',
          icon: <Lock className="w-3.5 h-3.5 text-[#94A3B8]" />,
          label: 'Locked'
        };
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-12 font-sans">
      {/* Header */}
      <div className="bg-white p-6 sm:p-8 rounded-xl border border-[#E2E8F0] shadow-card flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold px-2.5 py-1 rounded bg-[#F0FDFA] text-[#0F766E] border border-[#CCFBF1] uppercase tracking-wider">
              Step-by-Step Curriculum
            </span>
            <span className="text-xs text-[#64748B]">• Dynamic Roadmap</span>
          </div>
          <h1 className="text-2xl font-bold text-[#0F172A] tracking-tight mt-1">
            {selectedRole} Learning Path
          </h1>
          <p className="text-xs text-[#64748B] mt-0.5">
            Sequential milestones generated by AI to bridge your detected skill gaps systematically.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
          <div className="flex items-center gap-2 px-3 py-2 bg-white border border-[#CBD5E1] rounded-lg">
            <Target className="w-4 h-4 text-[#0F766E]" />
            <select
              value={selectedRole}
              onChange={(e) => setSelectedRole(e.target.value)}
              className="text-xs font-semibold bg-transparent text-[#0F172A] outline-none cursor-pointer"
            >
              <option value="Full-Stack Developer">Full-Stack Developer</option>
              <option value="Frontend Engineer">Frontend Engineer</option>
              <option value="Backend Engineer">Backend Engineer</option>
              <option value="AI / ML Engineer">AI / ML Engineer</option>
              <option value="Data Scientist">Data Scientist</option>
              <option value="DevOps & Cloud Specialist">DevOps & Cloud Specialist</option>
            </select>
          </div>

          <button
            type="button"
            onClick={() => navigate('/weekly-plan')}
            className="px-4 py-2 bg-[#0F766E] hover:bg-[#115E59] text-white rounded-lg text-xs font-semibold shadow-xs flex items-center gap-2 shrink-0 transition-colors"
          >
            <Calendar className="w-4 h-4" />
            <span>Weekly Schedule</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Visual Timeline Pipeline */}
      <div className="space-y-4 relative">
        {/* Left connecting vertical line for desktop */}
        <div className="hidden md:block absolute left-8 top-8 bottom-8 w-0.5 bg-[#E2E8F0] -z-0" />

        {roadmap.map((module, idx) => {
          const statusStyle = getStatusBadge(module.status);
          const isLocked = module.status.toLowerCase() === 'locked';

          return (
            <div
              key={module.id}
              className={`relative bg-white rounded-xl border transition-colors p-5 sm:p-6 shadow-card flex flex-col md:flex-row items-start md:items-center gap-5 z-10 ${
                module.status.toLowerCase() === 'in progress'
                  ? 'border-[#0F766E] ring-1 ring-[#0F766E]/20'
                  : 'border-[#E2E8F0] hover:border-[#CBD5E1]'
              }`}
            >
              {/* Step Counter Badge */}
              <div
                className={`w-10 h-10 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 shadow-xs ${
                  module.status.toLowerCase() === 'completed'
                    ? 'bg-[#DCFCE7] text-[#16A34A] border border-[#BBF7D0]'
                    : module.status.toLowerCase() === 'in progress'
                    ? 'bg-[#0F766E] text-white'
                    : module.status.toLowerCase() === 'recommended'
                    ? 'bg-[#FEF3C7] text-[#D97706] border border-[#FDE68A]'
                    : 'bg-[#F1F5F9] text-[#94A3B8] border border-[#E2E8F0]'
                }`}
              >
                {String(idx + 1).padStart(2, '0')}
              </div>

              {/* Center Info */}
              <div className="flex-1 space-y-2">
                <div className="flex flex-wrap items-center gap-2">
                  <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full border text-[11px] font-medium ${statusStyle.bg}`}>
                    {statusStyle.icon}
                    <span>{statusStyle.label}</span>
                  </span>

                  <span className="text-[11px] font-medium text-[#64748B] bg-[#F1F5F9] px-2 py-0.5 rounded">
                    {module.difficulty}
                  </span>

                  <span className="text-[11px] font-medium text-[#64748B] bg-[#F1F5F9] px-2 py-0.5 rounded flex items-center gap-1">
                    <Clock className="w-3 h-3 text-[#94A3B8]" />
                    {module.duration}
                  </span>
                </div>

                <h3 className="text-base font-semibold text-[#0F172A]">{module.title}</h3>
                <p className="text-xs text-[#64748B] leading-relaxed max-w-3xl">{module.description}</p>

                {/* Skill tags */}
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {module.skills?.map((s, i) => (
                    <span key={i} className="text-[10px] font-medium px-2 py-0.5 rounded bg-[#F1F5F9] text-[#0F172A] border border-[#E2E8F0]">
                      {s}
                    </span>
                  ))}
                </div>

                {/* Progress bar */}
                <div className="w-full max-w-md pt-1 space-y-1">
                  <div className="flex justify-between text-[10px] font-semibold text-[#64748B]">
                    <span>Module Progress</span>
                    <span className="text-[#0F172A]">{module.progress}%</span>
                  </div>
                  <div className="w-full h-1.5 bg-[#E2E8F0] rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full ${
                        module.progress === 100
                          ? 'bg-[#16A34A]'
                          : module.progress > 0
                          ? 'bg-[#0F766E]'
                          : 'bg-[#CBD5E1]'
                      }`}
                      style={{ width: `${module.progress}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <div className="shrink-0 w-full md:w-auto">
                <button
                  type="button"
                  disabled={isLocked}
                  onClick={() => navigate('/practice')}
                  className={`w-full md:w-auto px-4 py-2 rounded-lg text-xs font-semibold transition-colors flex items-center justify-center gap-1.5 ${
                    isLocked
                      ? 'bg-[#F1F5F9] text-[#94A3B8] border border-[#E2E8F0] cursor-not-allowed'
                      : module.status.toLowerCase() === 'in progress'
                      ? 'bg-[#0F766E] hover:bg-[#115E59] text-white shadow-xs'
                      : 'bg-white hover:bg-[#F8FAFC] text-[#0F172A] border border-[#CBD5E1]'
                  }`}
                >
                  <PlayCircle className="w-4 h-4" />
                  <span>{module.progress === 100 ? 'Review Module' : isLocked ? 'Locked' : 'Continue Module'}</span>
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Curated Resources section */}
      <div className="bg-white p-6 sm:p-8 rounded-xl border border-[#E2E8F0] shadow-card space-y-5">
        <div className="flex items-center justify-between border-b border-[#E2E8F0] pb-3">
          <div>
            <span className="text-xs font-bold text-[#0F766E] uppercase tracking-wider">High-Yield Materials</span>
            <h2 className="text-base font-bold text-[#0F172A] mt-0.5">Recommended Hand-Picked Learning Resources</h2>
          </div>
          <span className="text-xs text-[#64748B] hidden sm:inline">Matched to your current roadmap</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {resources.map((res) => (
            <ResourceCard
              key={res.id}
              title={res.title}
              type={res.type}
              duration={res.duration}
              skill={res.skill}
              level={res.level}
              url={res.url}
              rating={res.rating}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default LearningPath;
